# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QT_Simulator.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(991, 802)
        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(10, 250, 611, 541))
        self.graphicsView.setObjectName("graphicsView")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 521, 221))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 40, 501, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 30, 101, 19))
        self.label.setObjectName("label")
        self.lineEdit_startlat = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_startlat.setGeometry(QtCore.QRect(10, 50, 131, 25))
        self.lineEdit_startlat.setObjectName("lineEdit_startlat")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(170, 30, 111, 19))
        self.label_2.setObjectName("label_2")
        self.lineEdit_startlon = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_startlon.setGeometry(QtCore.QRect(170, 50, 131, 25))
        self.lineEdit_startlon.setText("")
        self.lineEdit_startlon.setObjectName("lineEdit_startlon")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(330, 30, 111, 19))
        self.label_3.setObjectName("label_3")
        self.lineEdit_startalt = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_startalt.setGeometry(QtCore.QRect(330, 50, 131, 25))
        self.lineEdit_startalt.setText("")
        self.lineEdit_startalt.setObjectName("lineEdit_startalt")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 130, 501, 81))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 101, 19))
        self.label_4.setObjectName("label_4")
        self.lineEdit_endlat = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_endlat.setGeometry(QtCore.QRect(10, 50, 131, 25))
        self.lineEdit_endlat.setObjectName("lineEdit_endlat")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(170, 30, 111, 19))
        self.label_5.setObjectName("label_5")
        self.lineEdit_endlon = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_endlon.setGeometry(QtCore.QRect(170, 50, 131, 25))
        self.lineEdit_endlon.setText("")
        self.lineEdit_endlon.setObjectName("lineEdit_endlon")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(330, 20, 171, 19))
        self.label_7.setObjectName("label_7")
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(630, 10, 351, 231))
        self.groupBox_4.setObjectName("groupBox_4")
        self.radioButton_steadystate = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_steadystate.setGeometry(QtCore.QRect(20, 40, 131, 23))
        self.radioButton_steadystate.setChecked(True)
        self.radioButton_steadystate.setObjectName("radioButton_steadystate")
        self.radioButton_windprofile = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_windprofile.setGeometry(QtCore.QRect(20, 120, 119, 23))
        self.radioButton_windprofile.setObjectName("radioButton_windprofile")
        self.radioButton_noaaGFS = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_noaaGFS.setGeometry(QtCore.QRect(20, 80, 119, 23))
        self.radioButton_noaaGFS.setChecked(False)
        self.radioButton_noaaGFS.setObjectName("radioButton_noaaGFS")
        self.lineEdit_windfilename = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_windfilename.setGeometry(QtCore.QRect(20, 180, 211, 25))
        self.lineEdit_windfilename.setObjectName("lineEdit_windfilename")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(20, 160, 68, 19))
        self.label_6.setObjectName("label_6")
        self.pushButton_windfilebrowse = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_windfilebrowse.setGeometry(QtCore.QRect(250, 180, 91, 31))
        self.pushButton_windfilebrowse.setObjectName("pushButton_windfilebrowse")
        self.groupBox_5 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_5.setGeometry(QtCore.QRect(630, 260, 351, 221))
        self.groupBox_5.setObjectName("groupBox_5")
        self.radioButton_presenttime = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_presenttime.setGeometry(QtCore.QRect(20, 30, 131, 23))
        self.radioButton_presenttime.setChecked(True)
        self.radioButton_presenttime.setObjectName("radioButton_presenttime")
        self.radioButton_customtime = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_customtime.setGeometry(QtCore.QRect(20, 70, 119, 23))
        self.radioButton_customtime.setObjectName("radioButton_customtime")
        self.lineEdit_month = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_month.setGeometry(QtCore.QRect(20, 170, 51, 25))
        self.lineEdit_month.setObjectName("lineEdit_month")
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setGeometry(QtCore.QRect(20, 150, 51, 19))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setGeometry(QtCore.QRect(80, 150, 51, 19))
        self.label_12.setObjectName("label_12")
        self.lineEdit_day = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_day.setGeometry(QtCore.QRect(80, 170, 51, 25))
        self.lineEdit_day.setObjectName("lineEdit_day")
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setGeometry(QtCore.QRect(140, 150, 51, 19))
        self.label_13.setObjectName("label_13")
        self.lineEdit_year = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_year.setGeometry(QtCore.QRect(140, 170, 51, 25))
        self.lineEdit_year.setObjectName("lineEdit_year")
        self.lineEdit_hour = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_hour.setGeometry(QtCore.QRect(20, 120, 51, 25))
        self.lineEdit_hour.setText("")
        self.lineEdit_hour.setObjectName("lineEdit_hour")
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setGeometry(QtCore.QRect(20, 100, 51, 19))
        self.label_14.setObjectName("label_14")
        self.groupBox_6 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_6.setGeometry(QtCore.QRect(630, 510, 351, 151))
        self.groupBox_6.setObjectName("groupBox_6")
        self.lineEdit_outfiledest = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_outfiledest.setGeometry(QtCore.QRect(10, 110, 211, 25))
        self.lineEdit_outfiledest.setObjectName("lineEdit_outfiledest")
        self.pushButton_outfilebrowse = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_outfilebrowse.setGeometry(QtCore.QRect(240, 110, 91, 31))
        self.pushButton_outfilebrowse.setObjectName("pushButton_outfilebrowse")
        self.label_8 = QtWidgets.QLabel(self.groupBox_6)
        self.label_8.setGeometry(QtCore.QRect(10, 90, 171, 19))
        self.label_8.setObjectName("label_8")
        self.lineEdit_outfilename = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_outfilename.setGeometry(QtCore.QRect(10, 50, 151, 25))
        self.lineEdit_outfilename.setText("")
        self.lineEdit_outfilename.setObjectName("lineEdit_outfilename")
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_9.setGeometry(QtCore.QRect(10, 30, 151, 19))
        self.label_9.setObjectName("label_9")
        self.groupBox_7 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_7.setGeometry(QtCore.QRect(630, 680, 351, 111))
        self.groupBox_7.setObjectName("groupBox_7")
        self.pushButton_Exit = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_Exit.setGeometry(QtCore.QRect(10, 70, 101, 31))
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.pushButton_run = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_run.setGeometry(QtCore.QRect(10, 30, 101, 31))
        self.pushButton_run.setObjectName("pushButton_run")
        self.lineEdit_timealoft = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_timealoft.setGeometry(QtCore.QRect(190, 60, 113, 25))
        self.lineEdit_timealoft.setObjectName("lineEdit_timealoft")
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        self.label_10.setGeometry(QtCore.QRect(190, 40, 121, 19))
        self.label_10.setObjectName("label_10")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Glider Simulation"))
        self.groupBox.setTitle(_translate("Dialog", "Input Coordinates"))
        self.groupBox_2.setTitle(_translate("Dialog", "Starting Position"))
        self.label.setText(_translate("Dialog", "Latitude"))
        self.label_2.setText(_translate("Dialog", "Longitude"))
        self.label_3.setText(_translate("Dialog", "Altitude (ft)"))
        self.groupBox_3.setTitle(_translate("Dialog", "Target End Location"))
        self.label_4.setText(_translate("Dialog", "Latitude"))
        self.label_5.setText(_translate("Dialog", "Longitude"))
        self.label_7.setText(_translate("Dialog", "Format: DDD.DDDDD°"))
        self.groupBox_4.setTitle(_translate("Dialog", "Wind Conditions"))
        self.radioButton_steadystate.setText(_translate("Dialog", "Steady State"))
        self.radioButton_windprofile.setText(_translate("Dialog", "Wind Profile"))
        self.radioButton_noaaGFS.setText(_translate("Dialog", "NOAA GFS"))
        self.label_6.setText(_translate("Dialog", "Filename"))
        self.pushButton_windfilebrowse.setText(_translate("Dialog", "Browse"))
        self.groupBox_5.setTitle(_translate("Dialog", "Date and Time"))
        self.radioButton_presenttime.setText(_translate("Dialog", "Present Time"))
        self.radioButton_customtime.setText(_translate("Dialog", "Custom "))
        self.label_11.setText(_translate("Dialog", "Month"))
        self.label_12.setText(_translate("Dialog", "Day"))
        self.label_13.setText(_translate("Dialog", "Year"))
        self.label_14.setText(_translate("Dialog", "Hour"))
        self.groupBox_6.setTitle(_translate("Dialog", "Output"))
        self.pushButton_outfilebrowse.setText(_translate("Dialog", "Browse"))
        self.label_8.setText(_translate("Dialog", "Output File Desitination"))
        self.label_9.setText(_translate("Dialog", "Output Filename"))
        self.groupBox_7.setTitle(_translate("Dialog", "Simulation"))
        self.pushButton_Exit.setText(_translate("Dialog", "Exit"))
        self.pushButton_run.setText(_translate("Dialog", "Run"))
        self.label_10.setText(_translate("Dialog", "Time Aloft (m)"))

